name: flow

on:
  workflow_dispatch:
  schedule:
     - cron: "0 * * * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content 
        uses: actions/checkout@v2 

      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: execute py script 
        run: |
          python update.py
      - name: commit and push    
        run: |-
          git diff
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Update README || exit 0
          git push
