name: Update Hacker News

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_news:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pytz

      - name: (DEBUG) Show README content BEFORE script runs
        run: |
          echo "--- README BEFORE ---"
          cat README.md
          echo "--- END README BEFORE ---"
          
      - name: Update README with Hacker News stories
        run: python scripts/update_hacker_news.py

      - name: (DEBUG) Show README content AFTER script runs
        run: |
          echo "--- README AFTER ---"
          cat README.md
          echo "--- END README AFTER ---"

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: update Hacker News stories"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
