
name: Auto Update README

on:
  schedule:
    - cron: "0 6 * * 0"

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python update_readme.py

      - name: Commit & Push changes
        run: |
          git config user.name "Null-Err0r"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README with HN & contact"
          git push

